dist: trusty

language: java

jdk:
- openjdk8

addons:
  sonarcloud:
    organization: "xyzrlee"
    token:
      secure: "$SONAR_TOKEN"

script:
- cd xmsger
- chmod +x mvnw
- ./mvnw clean install -Dmaven.javadoc.skip=true -B -V
- ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent org.jacoco:jacoco-maven-plugin:report package sonar:sonar

cache:
  directories:
  - '$HOME/.m2/repository'
  - '$HOME/.sonar/cache'
