dist: bionic

language: java

jdk:
- openjdk11

addons:
  sonarcloud:
    organization: "xyzrlee-github"
    token:
      secure: "$SONAR_TOKEN"

script:
- rm -f ${HOME}/.m2/settings.xml
- cd xmsger
- chmod +x mvnw
- ./mvnw clean install -Dmaven.test.skip=true -Dmaven.javadoc.skip=true --batch-mode --show-version
#- ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package org.jacoco:jacoco-maven-plugin:report
- sonar-scanner

cache:
  directories:
  - '$HOME/.m2/repository'
  - '$HOME/.sonar/cache'
