dist: bionic

language: java

jdk:
- openjdk8
- openjdk13

addons:
  sonarcloud:
    organization: "xyzrlee-github"
    token:
      secure: "$SONAR_TOKEN"

script:
- cd xmsger
- chmod +x mvnw
- ./mvnw clean install -Dmaven.test.skip=true -Dmaven.javadoc.skip=true --batch-mode --show-version --no-transfer-progress
- ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent org.jacoco:jacoco-maven-plugin:report package sonar:sonar

cache:
  directories:
  - '$HOME/.m2/repository'
  - '$HOME/.sonar/cache'
