dist: bionic

language: java

jdk:
- openjdk11

addons:
  sonarcloud:
    organization: "xyzrlee-github"
    token:
      secure: "$SONAR_TOKEN"

script:
- cd xmsger
- chmod +x mvnw
- ./mvnw clean install -Dmaven.test.skip=true -Dmaven.javadoc.skip=true --batch-mode --show-version --no-transfer-progress
- sonar-scanner

cache:
  directories:
  - '$HOME/.m2/repository'
  - '$HOME/.sonar/cache'
