name: test
on:
  push:
    branches: [ "*" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: cache-m2
        uses: actions/cache@v2
        with:
          path: "~/.m2"
          key: cache-m2-${{ hashFiles('xmsger/pom.xml') }}
      - name: build
        run: |
          cd xmsger
          chmod +x mvnw
          ./mvnw clean package -Dmaven.javadoc.skip=true --batch-mode --show-version
      - uses: LouisBrunner/checks-action@v1.1.1
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: test
          conclusion: ${{ job.status }}
          output: |
            {"summary":${{ steps.test.outputs.summary }}}
